// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface ShowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.ShowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional int64 start_time = 2;</code>
   */
  long getStartTime();
}
