apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: booking
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: main-service
          image: main-service:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.122.1:3306/CRUD_REST?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: HOST_IP
              value: 192.168.122.1
          ports:
            - containerPort: 8080
      restartPolicy: Always
