// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>optional string first_name = 3;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 4;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string email = 5;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string phone_number = 6;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phone_number = 6;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>repeated int32 places = 7;</code>
   */
  java.util.List<java.lang.Integer> getPlacesList();
  /**
   * <code>repeated int32 places = 7;</code>
   */
  int getPlacesCount();
  /**
   * <code>repeated int32 places = 7;</code>
   */
  int getPlaces(int index);
}
