// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface BookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.BookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string mes = 1;</code>
   */
  java.lang.String getMes();
  /**
   * <code>optional string mes = 1;</code>
   */
  com.google.protobuf.ByteString
      getMesBytes();

  /**
   * <code>optional string film_name = 2;</code>
   */
  java.lang.String getFilmName();
  /**
   * <code>optional string film_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFilmNameBytes();

  /**
   * <code>optional int64 start_time = 3;</code>
   */
  long getStartTime();

  /**
   * <code>optional string first_name = 4;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 5;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string email = 6;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string phone_number = 7;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phone_number = 7;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>repeated int32 places = 8;</code>
   */
  java.util.List<java.lang.Integer> getPlacesList();
  /**
   * <code>repeated int32 places = 8;</code>
   */
  int getPlacesCount();
  /**
   * <code>repeated int32 places = 8;</code>
   */
  int getPlaces(int index);

  /**
   * <code>optional int32 price = 9;</code>
   */
  int getPrice();
}
