// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface ShowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.ShowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 show_id = 1;</code>
   */
  int getShowId();

  /**
   * <code>optional int32 film_id = 2;</code>
   */
  int getFilmId();

  /**
   * <code>optional string film_name = 3;</code>
   */
  java.lang.String getFilmName();
  /**
   * <code>optional string film_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFilmNameBytes();

  /**
   * <code>optional int64 start_time = 4;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 end_time = 5;</code>
   */
  long getEndTime();

  /**
   * <code>optional int32 price = 6;</code>
   */
  int getPrice();

  /**
   * <code>repeated int32 places = 7;</code>
   */
  java.util.List<java.lang.Integer> getPlacesList();
  /**
   * <code>repeated int32 places = 7;</code>
   */
  int getPlacesCount();
  /**
   * <code>repeated int32 places = 7;</code>
   */
  int getPlaces(int index);
}
