// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public final class BookingProto {
  private BookingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_ShowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_ShowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_ShowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_ShowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_BookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_BookingRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBooking.proto\022\007booking\"\035\n\016DeleteRespon" +
      "se\022\013\n\003mes\030\001 \001(\t\"\026\n\006Filter\022\014\n\004keys\030\001 \003(\t\"" +
      "-\n\013ShowRequest\022\n\n\002id\030\001 \001(\005\022\022\n\nstart_time" +
      "\030\002 \001(\003\"\033\n\rDeleteRequest\022\n\n\002id\030\001 \001(\005\"\210\001\n\014" +
      "ShowResponse\022\017\n\007show_id\030\001 \001(\005\022\017\n\007film_id" +
      "\030\002 \001(\005\022\021\n\tfilm_name\030\003 \001(\t\022\022\n\nstart_time\030" +
      "\004 \001(\003\022\020\n\010end_time\030\005 \001(\003\022\r\n\005price\030\006 \001(\005\022\016" +
      "\n\006places\030\007 \003(\005\"\260\001\n\017BookingResponse\022\013\n\003me" +
      "s\030\001 \001(\t\022\021\n\tfilm_name\030\002 \001(\t\022\022\n\nstart_time" +
      "\030\003 \001(\003\022\022\n\nfirst_name\030\004 \001(\t\022\021\n\tlast_name\030",
      "\005 \001(\t\022\r\n\005email\030\006 \001(\t\022\024\n\014phone_number\030\007 \001" +
      "(\t\022\016\n\006places\030\010 \003(\005\022\r\n\005price\030\t \001(\005\"\214\001\n\016Bo" +
      "okingRequest\022\n\n\002id\030\001 \001(\005\022\022\n\nstart_time\030\002" +
      " \001(\003\022\022\n\nfirst_name\030\003 \001(\t\022\021\n\tlast_name\030\004 " +
      "\001(\t\022\r\n\005email\030\005 \001(\t\022\024\n\014phone_number\030\006 \001(\t" +
      "\022\016\n\006places\030\007 \003(\0052\320\002\n\016BookingService\0229\n\013G" +
      "etAllShows\022\017.booking.Filter\032\025.booking.Sh" +
      "owResponse\"\0000\001\0228\n\007GetShow\022\024.booking.Show" +
      "Request\032\025.booking.ShowResponse\"\000\022B\n\rDele" +
      "teBooking\022\026.booking.DeleteRequest\032\027.book",
      "ing.DeleteResponse\"\000\022B\n\013MakeBooking\022\027.bo" +
      "oking.BookingRequest\032\030.booking.BookingRe" +
      "sponse\"\000\022A\n\nGetBooking\022\027.booking.Booking" +
      "Request\032\030.booking.BookingResponse\"\000B0\n\032c" +
      "om.twomen.backend.bookingB\014BookingProtoP" +
      "\001\242\002\001Bb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_booking_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_booking_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_DeleteResponse_descriptor,
        new java.lang.String[] { "Mes", });
    internal_static_booking_Filter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_booking_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_Filter_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_booking_ShowRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_booking_ShowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_ShowRequest_descriptor,
        new java.lang.String[] { "Id", "StartTime", });
    internal_static_booking_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_booking_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_DeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_booking_ShowResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_booking_ShowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_ShowResponse_descriptor,
        new java.lang.String[] { "ShowId", "FilmId", "FilmName", "StartTime", "EndTime", "Price", "Places", });
    internal_static_booking_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_booking_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_BookingResponse_descriptor,
        new java.lang.String[] { "Mes", "FilmName", "StartTime", "FirstName", "LastName", "Email", "PhoneNumber", "Places", "Price", });
    internal_static_booking_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_booking_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_BookingRequest_descriptor,
        new java.lang.String[] { "Id", "StartTime", "FirstName", "LastName", "Email", "PhoneNumber", "Places", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
