// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
