// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

public interface DeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.DeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string mes = 1;</code>
   */
  java.lang.String getMes();
  /**
   * <code>optional string mes = 1;</code>
   */
  com.google.protobuf.ByteString
      getMesBytes();
}
