// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Booking.proto

package com.twomen.backend.booking;

/**
 * Protobuf type {@code booking.ShowResponse}
 */
public  final class ShowResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:booking.ShowResponse)
    ShowResponseOrBuilder {
  // Use ShowResponse.newBuilder() to construct.
  private ShowResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShowResponse() {
    showId_ = 0;
    filmId_ = 0;
    filmName_ = "";
    startTime_ = 0L;
    endTime_ = 0L;
    price_ = 0;
    places_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ShowResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            showId_ = input.readInt32();
            break;
          }
          case 16: {

            filmId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            filmName_ = s;
            break;
          }
          case 32: {

            startTime_ = input.readInt64();
            break;
          }
          case 40: {

            endTime_ = input.readInt64();
            break;
          }
          case 48: {

            price_ = input.readInt32();
            break;
          }
          case 56: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              places_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000040;
            }
            places_.add(input.readInt32());
            break;
          }
          case 58: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
              places_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000040;
            }
            while (input.getBytesUntilLimit() > 0) {
              places_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        places_ = java.util.Collections.unmodifiableList(places_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.twomen.backend.booking.BookingProto.internal_static_booking_ShowResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.twomen.backend.booking.BookingProto.internal_static_booking_ShowResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.twomen.backend.booking.ShowResponse.class, com.twomen.backend.booking.ShowResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SHOW_ID_FIELD_NUMBER = 1;
  private int showId_;
  /**
   * <code>optional int32 show_id = 1;</code>
   */
  public int getShowId() {
    return showId_;
  }

  public static final int FILM_ID_FIELD_NUMBER = 2;
  private int filmId_;
  /**
   * <code>optional int32 film_id = 2;</code>
   */
  public int getFilmId() {
    return filmId_;
  }

  public static final int FILM_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object filmName_;
  /**
   * <code>optional string film_name = 3;</code>
   */
  public java.lang.String getFilmName() {
    java.lang.Object ref = filmName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filmName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string film_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFilmNameBytes() {
    java.lang.Object ref = filmName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filmName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIME_FIELD_NUMBER = 4;
  private long startTime_;
  /**
   * <code>optional int64 start_time = 4;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 5;
  private long endTime_;
  /**
   * <code>optional int64 end_time = 5;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int PRICE_FIELD_NUMBER = 6;
  private int price_;
  /**
   * <code>optional int32 price = 6;</code>
   */
  public int getPrice() {
    return price_;
  }

  public static final int PLACES_FIELD_NUMBER = 7;
  private java.util.List<java.lang.Integer> places_;
  /**
   * <code>repeated int32 places = 7;</code>
   */
  public java.util.List<java.lang.Integer>
      getPlacesList() {
    return places_;
  }
  /**
   * <code>repeated int32 places = 7;</code>
   */
  public int getPlacesCount() {
    return places_.size();
  }
  /**
   * <code>repeated int32 places = 7;</code>
   */
  public int getPlaces(int index) {
    return places_.get(index);
  }
  private int placesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (showId_ != 0) {
      output.writeInt32(1, showId_);
    }
    if (filmId_ != 0) {
      output.writeInt32(2, filmId_);
    }
    if (!getFilmNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filmName_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(4, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(5, endTime_);
    }
    if (price_ != 0) {
      output.writeInt32(6, price_);
    }
    if (getPlacesList().size() > 0) {
      output.writeUInt32NoTag(58);
      output.writeUInt32NoTag(placesMemoizedSerializedSize);
    }
    for (int i = 0; i < places_.size(); i++) {
      output.writeInt32NoTag(places_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (showId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, showId_);
    }
    if (filmId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, filmId_);
    }
    if (!getFilmNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filmName_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, endTime_);
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, price_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < places_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(places_.get(i));
      }
      size += dataSize;
      if (!getPlacesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      placesMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.twomen.backend.booking.ShowResponse)) {
      return super.equals(obj);
    }
    com.twomen.backend.booking.ShowResponse other = (com.twomen.backend.booking.ShowResponse) obj;

    boolean result = true;
    result = result && (getShowId()
        == other.getShowId());
    result = result && (getFilmId()
        == other.getFilmId());
    result = result && getFilmName()
        .equals(other.getFilmName());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (getPrice()
        == other.getPrice());
    result = result && getPlacesList()
        .equals(other.getPlacesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SHOW_ID_FIELD_NUMBER;
    hash = (53 * hash) + getShowId();
    hash = (37 * hash) + FILM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFilmId();
    hash = (37 * hash) + FILM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilmName().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    if (getPlacesCount() > 0) {
      hash = (37 * hash) + PLACES_FIELD_NUMBER;
      hash = (53 * hash) + getPlacesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.twomen.backend.booking.ShowResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.twomen.backend.booking.ShowResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.twomen.backend.booking.ShowResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.twomen.backend.booking.ShowResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.twomen.backend.booking.ShowResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code booking.ShowResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:booking.ShowResponse)
      com.twomen.backend.booking.ShowResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.twomen.backend.booking.BookingProto.internal_static_booking_ShowResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.twomen.backend.booking.BookingProto.internal_static_booking_ShowResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.twomen.backend.booking.ShowResponse.class, com.twomen.backend.booking.ShowResponse.Builder.class);
    }

    // Construct using com.twomen.backend.booking.ShowResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      showId_ = 0;

      filmId_ = 0;

      filmName_ = "";

      startTime_ = 0L;

      endTime_ = 0L;

      price_ = 0;

      places_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.twomen.backend.booking.BookingProto.internal_static_booking_ShowResponse_descriptor;
    }

    public com.twomen.backend.booking.ShowResponse getDefaultInstanceForType() {
      return com.twomen.backend.booking.ShowResponse.getDefaultInstance();
    }

    public com.twomen.backend.booking.ShowResponse build() {
      com.twomen.backend.booking.ShowResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.twomen.backend.booking.ShowResponse buildPartial() {
      com.twomen.backend.booking.ShowResponse result = new com.twomen.backend.booking.ShowResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.showId_ = showId_;
      result.filmId_ = filmId_;
      result.filmName_ = filmName_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.price_ = price_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        places_ = java.util.Collections.unmodifiableList(places_);
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.places_ = places_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.twomen.backend.booking.ShowResponse) {
        return mergeFrom((com.twomen.backend.booking.ShowResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.twomen.backend.booking.ShowResponse other) {
      if (other == com.twomen.backend.booking.ShowResponse.getDefaultInstance()) return this;
      if (other.getShowId() != 0) {
        setShowId(other.getShowId());
      }
      if (other.getFilmId() != 0) {
        setFilmId(other.getFilmId());
      }
      if (!other.getFilmName().isEmpty()) {
        filmName_ = other.filmName_;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      if (!other.places_.isEmpty()) {
        if (places_.isEmpty()) {
          places_ = other.places_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensurePlacesIsMutable();
          places_.addAll(other.places_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.twomen.backend.booking.ShowResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.twomen.backend.booking.ShowResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int showId_ ;
    /**
     * <code>optional int32 show_id = 1;</code>
     */
    public int getShowId() {
      return showId_;
    }
    /**
     * <code>optional int32 show_id = 1;</code>
     */
    public Builder setShowId(int value) {
      
      showId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 show_id = 1;</code>
     */
    public Builder clearShowId() {
      
      showId_ = 0;
      onChanged();
      return this;
    }

    private int filmId_ ;
    /**
     * <code>optional int32 film_id = 2;</code>
     */
    public int getFilmId() {
      return filmId_;
    }
    /**
     * <code>optional int32 film_id = 2;</code>
     */
    public Builder setFilmId(int value) {
      
      filmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 film_id = 2;</code>
     */
    public Builder clearFilmId() {
      
      filmId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object filmName_ = "";
    /**
     * <code>optional string film_name = 3;</code>
     */
    public java.lang.String getFilmName() {
      java.lang.Object ref = filmName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filmName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string film_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFilmNameBytes() {
      java.lang.Object ref = filmName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string film_name = 3;</code>
     */
    public Builder setFilmName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filmName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string film_name = 3;</code>
     */
    public Builder clearFilmName() {
      
      filmName_ = getDefaultInstance().getFilmName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string film_name = 3;</code>
     */
    public Builder setFilmNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filmName_ = value;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>optional int64 start_time = 4;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>optional int64 start_time = 4;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 start_time = 4;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int price_ ;
    /**
     * <code>optional int32 price = 6;</code>
     */
    public int getPrice() {
      return price_;
    }
    /**
     * <code>optional int32 price = 6;</code>
     */
    public Builder setPrice(int value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 price = 6;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> places_ = java.util.Collections.emptyList();
    private void ensurePlacesIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        places_ = new java.util.ArrayList<java.lang.Integer>(places_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public java.util.List<java.lang.Integer>
        getPlacesList() {
      return java.util.Collections.unmodifiableList(places_);
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public int getPlacesCount() {
      return places_.size();
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public int getPlaces(int index) {
      return places_.get(index);
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public Builder setPlaces(
        int index, int value) {
      ensurePlacesIsMutable();
      places_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public Builder addPlaces(int value) {
      ensurePlacesIsMutable();
      places_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public Builder addAllPlaces(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePlacesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, places_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 places = 7;</code>
     */
    public Builder clearPlaces() {
      places_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:booking.ShowResponse)
  }

  // @@protoc_insertion_point(class_scope:booking.ShowResponse)
  private static final com.twomen.backend.booking.ShowResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.twomen.backend.booking.ShowResponse();
  }

  public static com.twomen.backend.booking.ShowResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShowResponse>
      PARSER = new com.google.protobuf.AbstractParser<ShowResponse>() {
    public ShowResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShowResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShowResponse> getParserForType() {
    return PARSER;
  }

  public com.twomen.backend.booking.ShowResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

